---
name: main

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'

      - name: Cache
        uses: actions/cache@v2
        with:
          path:         |
                        ~/go/pkg/mod
          key:          ${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
                        ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                        ${{ runner.os }}-go-

      - name: Test
        run:  go test -failfast ./...

  docker:

    runs-on: ubuntu-latest

    needs:
      - test

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id:   meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images:     ${{ github.repository }}
          tag-semver: |
                      {{version}}
                      {{major}}.{{minor}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context:   .
          file:      ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push:      ${{ github.event_name != 'pull_request' }}
          tags:      ${{ steps.meta.outputs.tags }}
          labels:    ${{ steps.meta.outputs.labels }}
